# Generated by Django 3.2.7 on 2021-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210907_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channelTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
